-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgppGLhhy5Ch443FzL
oqbKnmopDSYrbyFjmoQzW8TiXrSgCgYIKoZIzj0DAQehRANCAARvc3qCVqkStso3
C1Lcu9Scw8GtsLpBPQjtZH914xks+Obca1SexpMK9jKOJCcFKnSUvk5inEZTYfkD
I04dIlQ8
-----END PRIVATE KEY-----