// Writes the generated CDN constants into each client repo.
//   bun src/codegen.ts                      write into the default checkouts
//   bun src/codegen.ts --check              exit 1 if any target is stale
//   bun src/codegen.ts --fe=<dir> --public=<dir> --rn=<dir> --be=<dir>
//                                           point at worktrees instead
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { ALIASES, ASSETS, CDN_BASE_URL } from "./manifest";
import { assertManifest, MONOREPO_ROOT } from "./lib";

interface Target {
  name: string;
  repo: string;
  file: string;
  quote: '"' | "'";
  /** Top-level groups to emit; undefined = all. */
  groups?: string[];
  /** Also emit the legacy-path map and placeholder list (DB migrations need them). */
  migrationMaps?: boolean;
}

const arg = (n: string) => process.argv.find((a) => a.startsWith(`--${n}=`))?.split("=")[1];
const repoDir = (n: string, fallback: string) => resolve(arg(n) ?? join(MONOREPO_ROOT, fallback));

const TARGETS: Target[] = [
  { name: "fe", repo: repoDir("fe", "pawjai-fe"), file: "lib/constants/cdnAssets.generated.ts", quote: '"' },
  { name: "public", repo: repoDir("public", "pawjai-public"), file: "src/lib/constants/cdnAssets.generated.ts", quote: '"' },
  { name: "rn", repo: repoDir("rn", "pawjai-react-native"), file: "src/design-system/assets/cdnAssets.generated.ts", quote: "'" },
  { name: "be", repo: repoDir("be", "pawjai-be"), file: "src/constants/cdnAssets.generated.ts", quote: "'", groups: ["RECORD_ICONS", "LOOKUP_ICONS"], migrationMaps: true },
];

// key -> storage path, aliases resolved
function keyPaths(): Map<string, string> {
  const m = new Map<string, string>();
  for (const a of ASSETS) for (const k of a.keys ?? []) m.set(k, a.to);
  for (const [alias, target] of Object.entries(ALIASES)) {
    const p = m.get(target);
    if (!p) throw new Error(`alias ${alias} -> unknown key ${target}`);
    m.set(alias, p);
  }
  return m;
}

type Tree = { [k: string]: Tree | string };

function buildTree(paths: Map<string, string>, groups?: string[]): Tree {
  const root: Tree = {};
  for (const [key, path] of paths) {
    const [group, ...rest] = key.split(".");
    if (groups && !groups.includes(group)) continue;
    // RECORD_ICONS is a flat map keyed by catalog id ("symptom.vomiting.dog").
    const segs = group === "RECORD_ICONS" ? [group, rest.join(".")] : [group, ...rest];
    let node = root;
    for (const s of segs.slice(0, -1)) node = (node[s] ??= {}) as Tree;
    node[segs[segs.length - 1]] = path;
  }
  return root;
}

const IDENT = /^[A-Za-z_$][\w$]*$/;
function emit(node: Tree, q: string, depth: number): string {
  const pad = "  ".repeat(depth);
  const lines = Object.keys(node)
    .sort()
    .map((k) => {
      const v = node[k];
      const key = IDENT.test(k) ? k : `${q}${k}${q}`;
      return typeof v === "string"
        ? `${pad}  ${key}: \`\${CDN_BASE_URL}/${v}\`,`
        : `${pad}  ${key}: ${emit(v, q, depth + 1)},`;
    });
  return `{\n${lines.join("\n")}\n${pad}}`;
}

function migrationMaps(q: string): string[] {
  const legacy = ASSETS.flatMap((a) => [...(a.from ? [a.from] : []), ...(a.alsoAt ?? [])].map((from) => [decodeURIComponent(from), a.to]))
    .map(([from, to]) => `  ${q}${from}${q}: ${q}${to}${q},`)
    .sort();
  const placeholders = ASSETS.filter((a) => a.placeholder)
    .map((a) => `  ${q}${a.to}${q},`)
    .sort();
  return [
    "/** Legacy CDN path -> static/ path, for migrating stored URLs. */",
    `export const LEGACY_PATH_TO_STATIC: Record<string, string> = {\n${legacy.join("\n")}\n};\n`,
    "/** static/ paths that currently hold placeholder art (real art not made yet). */",
    `export const PLACEHOLDER_PATHS: ReadonlySet<string> = new Set([\n${placeholders.join("\n")}\n]);\n`,
  ];
}

function render(t: Target): string {
  const q = t.quote;
  const tree = buildTree(keyPaths(), t.groups);
  const groups = Object.keys(tree).sort();
  return [
    "// GENERATED by tools/cdn-assets (parent pawjai repo): `bun run codegen`.",
    "// Do not edit by hand; change tools/cdn-assets/src/manifest.ts instead.",
    "",
    `export const CDN_BASE_URL = ${q}${CDN_BASE_URL}${q};`,
    "",
    ...groups.map((g) => `export const ${g} = ${emit(tree[g] as Tree, q, 0)} as const;\n`),
    ...(t.migrationMaps ? migrationMaps(q) : []),
  ].join("\n");
}

assertManifest();
const check = process.argv.includes("--check");
let stale = 0;
for (const t of TARGETS) {
  if (!existsSync(t.repo)) {
    console.log(`skip ${t.name}: ${t.repo} missing`);
    continue;
  }
  const dest = join(t.repo, t.file);
  const next = render(t);
  const cur = existsSync(dest) ? readFileSync(dest, "utf8") : null;
  if (cur === next) {
    console.log(`ok    ${t.name} ${dest}`);
    continue;
  }
  if (check) {
    stale++;
    console.log(`STALE ${t.name} ${dest}`);
    continue;
  }
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, next);
  console.log(`wrote ${t.name} ${dest}`);
}
if (stale) process.exit(1);
